// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Student_management.Models;

#nullable disable

namespace Student_management.Migrations
{
    [DbContext(typeof(QuanLyHocSinhContext))]
    [Migration("20250901171519_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Student_management.Models.Diem", b =>
                {
                    b.Property<int>("MaDiem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDiem"));

                    b.Property<double?>("Diem15p")
                        .HasColumnType("float");

                    b.Property<double?>("Diem1Tiet")
                        .HasColumnType("float");

                    b.Property<double?>("DiemMieng")
                        .HasColumnType("float");

                    b.Property<double?>("DiemThi")
                        .HasColumnType("float");

                    b.Property<int>("MaHk")
                        .HasColumnType("int")
                        .HasColumnName("MaHK");

                    b.Property<int>("MaHs")
                        .HasColumnType("int")
                        .HasColumnName("MaHS");

                    b.Property<int>("MaMonHoc")
                        .HasColumnType("int");

                    b.HasKey("MaDiem")
                        .HasName("PK__DIEM__33326025B95668FD");

                    b.HasIndex("MaHk");

                    b.HasIndex("MaHs");

                    b.HasIndex("MaMonHoc");

                    b.ToTable("DIEM", (string)null);
                });

            modelBuilder.Entity("Student_management.Models.Giaovien", b =>
                {
                    b.Property<int>("MaGv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaGV");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGv"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaMonHoc")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sdt")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("SDT");

                    b.HasKey("MaGv")
                        .HasName("PK__GIAOVIEN__2725AEF30D4C2168");

                    b.HasIndex("MaMonHoc");

                    b.ToTable("GIAOVIEN", (string)null);
                });

            modelBuilder.Entity("Student_management.Models.Hocky", b =>
                {
                    b.Property<int>("MaHk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaHK");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHk"));

                    b.Property<int>("MaNamHoc")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenHk")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenHK");

                    b.HasKey("MaHk")
                        .HasName("PK__HOCKY__2725A6E74A815533");

                    b.HasIndex("MaNamHoc");

                    b.ToTable("HOCKY", (string)null);
                });

            modelBuilder.Entity("Student_management.Models.Hocphi", b =>
                {
                    b.Property<int>("MaHp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaHP");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHp"));

                    b.Property<int>("MaHk")
                        .HasColumnType("int")
                        .HasColumnName("MaHK");

                    b.Property<int>("MaHs")
                        .HasColumnType("int")
                        .HasColumnName("MaHS");

                    b.Property<DateTime>("NgayDong")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("SoTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaHp")
                        .HasName("PK__HOCPHI__2725A6EC27BADE72");

                    b.HasIndex("MaHk");

                    b.HasIndex("MaHs");

                    b.ToTable("HOCPHI", (string)null);
                });

            modelBuilder.Entity("Student_management.Models.Hocsinh", b =>
                {
                    b.Property<int>("MaHs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaHS");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHs"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaLop")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sdt")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("SDT");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaHs")
                        .HasName("PK__HOCSINH__2725A6EFD23810DA");

                    b.HasIndex("MaLop");

                    b.ToTable("HOCSINH", (string)null);
                });

            modelBuilder.Entity("Student_management.Models.Lichhoc", b =>
                {
                    b.Property<int>("MaLichHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichHoc"));

                    b.Property<int>("MaGv")
                        .HasColumnType("int")
                        .HasColumnName("MaGV");

                    b.Property<int>("MaHk")
                        .HasColumnType("int")
                        .HasColumnName("MaHK");

                    b.Property<int>("MaLop")
                        .HasColumnType("int");

                    b.Property<int>("MaMonHoc")
                        .HasColumnType("int");

                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.Property<string>("ThuTrongTuan")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TietHoc")
                        .HasColumnType("int");

                    b.HasKey("MaLichHoc")
                        .HasName("PK__LICHHOC__150EBC217240C5E5");

                    b.HasIndex("MaGv");

                    b.HasIndex("MaHk");

                    b.HasIndex("MaLop");

                    b.HasIndex("MaMonHoc");

                    b.HasIndex("MaPhong");

                    b.ToTable("LICHHOC", (string)null);
                });

            modelBuilder.Entity("Student_management.Models.Lop", b =>
                {
                    b.Property<int>("MaLop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLop"));

                    b.Property<int?>("MaGvcn")
                        .HasColumnType("int")
                        .HasColumnName("MaGVCN");

                    b.Property<int>("MaNamHoc")
                        .HasColumnType("int");

                    b.Property<int?>("SiSo")
                        .HasColumnType("int");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLop")
                        .HasName("PK__LOP__3B98D273DE505D17");

                    b.HasIndex("MaGvcn");

                    b.HasIndex("MaNamHoc");

                    b.ToTable("LOP", (string)null);
                });

            modelBuilder.Entity("Student_management.Models.Monhoc", b =>
                {
                    b.Property<int>("MaMonHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaMonHoc"));

                    b.Property<double?>("HeSo")
                        .HasColumnType("float");

                    b.Property<int?>("SoTiet")
                        .HasColumnType("int");

                    b.Property<string>("TenMonHoc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaMonHoc")
                        .HasName("PK__MONHOC__4127737F4381EA57");

                    b.ToTable("MONHOC", (string)null);
                });

            modelBuilder.Entity("Student_management.Models.Namhoc", b =>
                {
                    b.Property<int>("MaNamHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNamHoc"));

                    b.Property<DateOnly>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateOnly>("NgayKetThuc")
                        .HasColumnType("date");

                    b.Property<string>("TenNamHoc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaNamHoc")
                        .HasName("PK__NAMHOC__7DBADD74A20088A1");

                    b.ToTable("NAMHOC", (string)null);
                });

            modelBuilder.Entity("Student_management.Models.PhancongGiangday", b =>
                {
                    b.Property<int>("MaPc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaPC");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPc"));

                    b.Property<int>("MaGv")
                        .HasColumnType("int")
                        .HasColumnName("MaGV");

                    b.Property<int>("MaHk")
                        .HasColumnType("int")
                        .HasColumnName("MaHK");

                    b.Property<int>("MaLop")
                        .HasColumnType("int");

                    b.Property<int>("MaMonHoc")
                        .HasColumnType("int");

                    b.HasKey("MaPc")
                        .HasName("PK__PHANCONG__2725E7E5CD65F42C");

                    b.HasIndex("MaGv");

                    b.HasIndex("MaHk");

                    b.HasIndex("MaLop");

                    b.HasIndex("MaMonHoc");

                    b.ToTable("PHANCONG_GIANGDAY", (string)null);
                });

            modelBuilder.Entity("Student_management.Models.Phonghoc", b =>
                {
                    b.Property<int>("MaPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhong"));

                    b.Property<int?>("SucChua")
                        .HasColumnType("int");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ViTri")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaPhong")
                        .HasName("PK__PHONGHOC__20BD5E5BFA4C78DA");

                    b.ToTable("PHONGHOC", (string)null);
                });

            modelBuilder.Entity("Student_management.Models.Taikhoan", b =>
                {
                    b.Property<int>("MaTk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaTK");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTk"));

                    b.Property<int?>("MaGv")
                        .HasColumnType("int")
                        .HasColumnName("MaGV");

                    b.Property<int?>("MaHs")
                        .HasColumnType("int")
                        .HasColumnName("MaHS");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaTk")
                        .HasName("PK__TAIKHOAN__272500708AF1A976");

                    b.HasIndex("MaGv");

                    b.HasIndex("MaHs");

                    b.HasIndex(new[] { "TenDangNhap" }, "UQ__TAIKHOAN__55F68FC092A2A6BA")
                        .IsUnique();

                    b.ToTable("TAIKHOAN", (string)null);
                });

            modelBuilder.Entity("Student_management.Models.Diem", b =>
                {
                    b.HasOne("Student_management.Models.Hocky", "MaHkNavigation")
                        .WithMany("Diems")
                        .HasForeignKey("MaHk")
                        .IsRequired()
                        .HasConstraintName("FK_DIEM_HOCKY");

                    b.HasOne("Student_management.Models.Hocsinh", "MaHsNavigation")
                        .WithMany("Diems")
                        .HasForeignKey("MaHs")
                        .IsRequired()
                        .HasConstraintName("FK_DIEM_HOCSINH");

                    b.HasOne("Student_management.Models.Monhoc", "MaMonHocNavigation")
                        .WithMany("Diems")
                        .HasForeignKey("MaMonHoc")
                        .IsRequired()
                        .HasConstraintName("FK_DIEM_MONHOC");

                    b.Navigation("MaHkNavigation");

                    b.Navigation("MaHsNavigation");

                    b.Navigation("MaMonHocNavigation");
                });

            modelBuilder.Entity("Student_management.Models.Giaovien", b =>
                {
                    b.HasOne("Student_management.Models.Monhoc", "MaMonHocNavigation")
                        .WithMany("Giaoviens")
                        .HasForeignKey("MaMonHoc")
                        .HasConstraintName("FK_GIAOVIEN_MONHOC");

                    b.Navigation("MaMonHocNavigation");
                });

            modelBuilder.Entity("Student_management.Models.Hocky", b =>
                {
                    b.HasOne("Student_management.Models.Namhoc", "MaNamHocNavigation")
                        .WithMany("Hockies")
                        .HasForeignKey("MaNamHoc")
                        .IsRequired()
                        .HasConstraintName("FK_HOCKY_NAMHOC");

                    b.Navigation("MaNamHocNavigation");
                });

            modelBuilder.Entity("Student_management.Models.Hocphi", b =>
                {
                    b.HasOne("Student_management.Models.Hocky", "MaHkNavigation")
                        .WithMany("Hocphis")
                        .HasForeignKey("MaHk")
                        .IsRequired()
                        .HasConstraintName("FK_HP_HOCKY");

                    b.HasOne("Student_management.Models.Hocsinh", "MaHsNavigation")
                        .WithMany("Hocphis")
                        .HasForeignKey("MaHs")
                        .IsRequired()
                        .HasConstraintName("FK_HP_HOCSINH");

                    b.Navigation("MaHkNavigation");

                    b.Navigation("MaHsNavigation");
                });

            modelBuilder.Entity("Student_management.Models.Hocsinh", b =>
                {
                    b.HasOne("Student_management.Models.Lop", "MaLopNavigation")
                        .WithMany("Hocsinhs")
                        .HasForeignKey("MaLop")
                        .IsRequired()
                        .HasConstraintName("FK_HOCSINH_LOP");

                    b.Navigation("MaLopNavigation");
                });

            modelBuilder.Entity("Student_management.Models.Lichhoc", b =>
                {
                    b.HasOne("Student_management.Models.Giaovien", "MaGvNavigation")
                        .WithMany("Lichhocs")
                        .HasForeignKey("MaGv")
                        .IsRequired()
                        .HasConstraintName("FK_LH_GIAOVIEN");

                    b.HasOne("Student_management.Models.Hocky", "MaHkNavigation")
                        .WithMany("Lichhocs")
                        .HasForeignKey("MaHk")
                        .IsRequired()
                        .HasConstraintName("FK_LH_HOCKY");

                    b.HasOne("Student_management.Models.Lop", "MaLopNavigation")
                        .WithMany("Lichhocs")
                        .HasForeignKey("MaLop")
                        .IsRequired()
                        .HasConstraintName("FK_LH_LOP");

                    b.HasOne("Student_management.Models.Monhoc", "MaMonHocNavigation")
                        .WithMany("Lichhocs")
                        .HasForeignKey("MaMonHoc")
                        .IsRequired()
                        .HasConstraintName("FK_LH_MONHOC");

                    b.HasOne("Student_management.Models.Phonghoc", "MaPhongNavigation")
                        .WithMany("Lichhocs")
                        .HasForeignKey("MaPhong")
                        .IsRequired()
                        .HasConstraintName("FK_LH_PHONGHOC");

                    b.Navigation("MaGvNavigation");

                    b.Navigation("MaHkNavigation");

                    b.Navigation("MaLopNavigation");

                    b.Navigation("MaMonHocNavigation");

                    b.Navigation("MaPhongNavigation");
                });

            modelBuilder.Entity("Student_management.Models.Lop", b =>
                {
                    b.HasOne("Student_management.Models.Giaovien", "MaGvcnNavigation")
                        .WithMany("Lops")
                        .HasForeignKey("MaGvcn")
                        .HasConstraintName("FK_LOP_GIAOVIEN");

                    b.HasOne("Student_management.Models.Namhoc", "MaNamHocNavigation")
                        .WithMany("Lops")
                        .HasForeignKey("MaNamHoc")
                        .IsRequired()
                        .HasConstraintName("FK_LOP_NAMHOC");

                    b.Navigation("MaGvcnNavigation");

                    b.Navigation("MaNamHocNavigation");
                });

            modelBuilder.Entity("Student_management.Models.PhancongGiangday", b =>
                {
                    b.HasOne("Student_management.Models.Giaovien", "MaGvNavigation")
                        .WithMany("PhancongGiangdays")
                        .HasForeignKey("MaGv")
                        .IsRequired()
                        .HasConstraintName("FK_PC_GIAOVIEN");

                    b.HasOne("Student_management.Models.Hocky", "MaHkNavigation")
                        .WithMany("PhancongGiangdays")
                        .HasForeignKey("MaHk")
                        .IsRequired()
                        .HasConstraintName("FK_PC_HOCKY");

                    b.HasOne("Student_management.Models.Lop", "MaLopNavigation")
                        .WithMany("PhancongGiangdays")
                        .HasForeignKey("MaLop")
                        .IsRequired()
                        .HasConstraintName("FK_PC_LOP");

                    b.HasOne("Student_management.Models.Monhoc", "MaMonHocNavigation")
                        .WithMany("PhancongGiangdays")
                        .HasForeignKey("MaMonHoc")
                        .IsRequired()
                        .HasConstraintName("FK_PC_MONHOC");

                    b.Navigation("MaGvNavigation");

                    b.Navigation("MaHkNavigation");

                    b.Navigation("MaLopNavigation");

                    b.Navigation("MaMonHocNavigation");
                });

            modelBuilder.Entity("Student_management.Models.Taikhoan", b =>
                {
                    b.HasOne("Student_management.Models.Giaovien", "MaGvNavigation")
                        .WithMany("Taikhoans")
                        .HasForeignKey("MaGv")
                        .HasConstraintName("FK_TK_GIAOVIEN");

                    b.HasOne("Student_management.Models.Hocsinh", "MaHsNavigation")
                        .WithMany("Taikhoans")
                        .HasForeignKey("MaHs")
                        .HasConstraintName("FK_TK_HOCSINH");

                    b.Navigation("MaGvNavigation");

                    b.Navigation("MaHsNavigation");
                });

            modelBuilder.Entity("Student_management.Models.Giaovien", b =>
                {
                    b.Navigation("Lichhocs");

                    b.Navigation("Lops");

                    b.Navigation("PhancongGiangdays");

                    b.Navigation("Taikhoans");
                });

            modelBuilder.Entity("Student_management.Models.Hocky", b =>
                {
                    b.Navigation("Diems");

                    b.Navigation("Hocphis");

                    b.Navigation("Lichhocs");

                    b.Navigation("PhancongGiangdays");
                });

            modelBuilder.Entity("Student_management.Models.Hocsinh", b =>
                {
                    b.Navigation("Diems");

                    b.Navigation("Hocphis");

                    b.Navigation("Taikhoans");
                });

            modelBuilder.Entity("Student_management.Models.Lop", b =>
                {
                    b.Navigation("Hocsinhs");

                    b.Navigation("Lichhocs");

                    b.Navigation("PhancongGiangdays");
                });

            modelBuilder.Entity("Student_management.Models.Monhoc", b =>
                {
                    b.Navigation("Diems");

                    b.Navigation("Giaoviens");

                    b.Navigation("Lichhocs");

                    b.Navigation("PhancongGiangdays");
                });

            modelBuilder.Entity("Student_management.Models.Namhoc", b =>
                {
                    b.Navigation("Hockies");

                    b.Navigation("Lops");
                });

            modelBuilder.Entity("Student_management.Models.Phonghoc", b =>
                {
                    b.Navigation("Lichhocs");
                });
#pragma warning restore 612, 618
        }
    }
}
